fix: json serialization for jsonb (#2713)
## :wrench: Problem

There is an error in the component admin when trying to load components.

## :cake: Solution

When moving to Pydantic, I overlooked the serialization of the jsonb
fields. When they are no Pydantic models to serialize too, we should
still decode the json string to an object (that was the cause of the
error: Elm was getting a string instead of a dict).


## :rotating_light:  Points to watch/comments

I’ve simplified some tests too and I’ve properly implemented the string
serialization of the `JournalEntry` value (as it should be a dict but
serialized as a string for the Elm frontend)

## :desert_island: How to test

Go to the Admin in the components section : it should display the list
of components as expected.