chore: pin python version to 3.12.x to avoid psycopg-binary incompatibility (#1425)
## :wrench: Problem

We have an error when deploying the app because `psycopg-binary` doesn't
have wheels on python 3.14 which was recently released :
```
error: Distribution `psycopg-binary==3.2.9 @ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform
```

## :cake: Solution

Pin the python version to 3.12.x

## :rotating_light:  Points to watch/comments

> _If there is anything unusual or some clarifications needed for the
reviewer to better understand the PR, discuss it here._

## :desert_island: How to test

> _What someone else than you should do to validate that the solution
you implemented is working as expected. Don't hesitate to be too verbose
and to explain in details, using bullet points for example, the steps to
follow to test the expected behavior._